export const interiors = [
  { id: 1, name: '빅브라더' },
  { id: 2, name: '도미노 게임' },
  { id: 3, name: '올가미' },
  { id: 4, name: '입' },
  { id: 5, name: '선생님' },
  { id: 6, name: '어리석은 승부' },
  { id: 7, name: '평등' },
  { id: 8, name: '사악한 책' },
  { id: 9, name: '이기심' },
  { id: 10, name: '나침반 바늘' },
  { id: 11, name: '빅브라더' },
  { id: 12, name: '도미노 게임' },
  { id: 13, name: '올가미' },
  { id: 14, name: '입' },
  { id: 15, name: '선생님' },
  { id: 16, name: '어리석은 승부' },
  { id: 17, name: '평등' },
  { id: 18, name: '사악한 책' },
  { id: 19, name: '이기심' },
  { id: 20, name: '나침반 바늘' },
  { id: 21, name: '빅브라더' },
  { id: 22, name: '도미노 게임' },
  { id: 23, name: '올가미' },
  { id: 24, name: '입' },
  { id: 25, name: '선생님' },
  { id: 26, name: '어리석은 승부' },
  { id: 27, name: '평등' },
  { id: 28, name: '사악한 책' },
  { id: 29, name: '이기심' },
  { id: 30, name: '나침반 바늘' },
  { id: 31, name: '빅브라더' },
  { id: 32, name: '도미노 게임' },
  { id: 33, name: '올가미' },
  { id: 34, name: '입' },
  { id: 35, name: '선생님' },
  { id: 36, name: '어리석은 승부' },
  { id: 37, name: '평등' },
  { id: 38, name: '사악한 책' },
  { id: 39, name: '이기심' },
  { id: 40, name: '나침반 바늘' },
  { id: 41, name: '빅브라더' },
  { id: 42, name: '도미노 게임' },
  { id: 43, name: '올가미' },
  { id: 44, name: '입' },
  { id: 45, name: '선생님' },
  { id: 46, name: '어리석은 승부' },
  { id: 47, name: '평등' },
  { id: 48, name: '사악한 책' },
  { id: 49, name: '이기심' },
  { id: 50, name: '나침반 바늘' },
];
